theme: jekyll-theme-hydejack
baseurl: ''
accent_image: /assets/img/sidebar-bg.jpg
accent_color: '#A85641'
font:         "'Noto Sans', Helvetica, Arial, sans-serif"
font_heading: "'Roboto Slab', Helvetica, Arial, sans-serif"
google_fonts: "Roboto+Slab:700|Noto+Sans:400,400i,700,700i"
plugins:
  - jekyll-paginate
  - jekyll-avatar
paginate:      5
paginate_path: '/page-:num/'
author:
  name:  Sritanu Chakraborty
  email: sritanu25@gmail.com
markdown: kramdown
exclude: ['README.md']
